### ISSUE TITLE
[Feature] Dark theme option

### ISSUE THREAD

**Issue by Nerd00F** [daltonmenezes/stylish-hub#1]
Option to enable dark theme on github with this add-on

**Comment by daltonmenezes** [comment]
@Nerd0000 Good suggestion. Please, edit the body of your message to English.
Maybe we can handle dark theme by creating a switch button in the header beside the notification icon. How about [Material-UI](https://material-ui.com/) approach?

**Comment by Nerd0000** [comment]
Translated

**Comment by daltonmenezes** [comment]
For our happiness, GitHub already has a dark theme mode. 🎉

**Comment by hisirdox** [comment]
yeah, now it has 🙂
