### ISSUE TITLE
[Feature] Show the number of merges and pull requests on the issues menu

### ISSUE THREAD

**Issue by Nerd0000** [daltonmenezes/stylish-hub#2]
<img src="https://drive.google.com/uc?id=1HY6JYc4AdV5Skgk8rp43SKMbpTWostQD"></img>

**Comment by daltonmenezes** [comment]
Hi @Nerd0000 , the provided image is broken. About the title, my question is, is it really a good idea? My fear is about put a lot of features that needs to use api requests and it can be a problem if a user have all other features blocked because of it. What do you think?

**Comment by Nerd0000** [comment]
Yeah, i think you are right.
I just thought it could be a good feature..

But the tecnologies behind it could not work well...

**Comment by daltonmenezes** [comment]
@Nerd0000 No prob, all feature requests will be always appreciated. For now, I'm going to close this one, but we can open it again if necessary in the future. Thanks a lot, I hope to start to working in your "Dark Theme" feature request as soon as possible.
