### ISSUE TITLE
[Error] Profile navigation

### ISSUE THREAD

**Issue by jos3s** [daltonmenezes/stylish-hub#3]
Expected view:
![Anotação 2020-04-02 092058](https://user-images.githubusercontent.com/50359547/78248593-5020e800-74c3-11ea-874d-c22656bf7ac9.jpg)
Current view:
![Anotação 2020-04-02 092108](https://user-images.githubusercontent.com/50359547/78248600-52834200-74c3-11ea-803c-1b6b75b877bf.jpg)
The error occurs only when using the [Refined Github](https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf)  extension together

**Comment by daltonmenezes** [comment]
Hi @jos3s , the point is: this is not a bug/error from Stylish-hub. Refined Github adds "Gists" at the end of list also and unlike it, Stylish-hub gives you the number of gists, Refined Github not.
